#!/bin/bash

. .env

HOST=${DOCKER_PGHOST:-$HOST}

# create schema
PGPASSWORD=$PASSWORDADMIN psql -h $HOST -p $PORT -U $ADMINUSER -d $DATABASE -c "CREATE SCHEMA $SCHEMA;"

# create tables
export PGOPTIONS="--search_path=$SCHEMA"
PGPASSWORD=$PASSWORDADMIN psql -h $HOST -p $PORT -U $ADMINUSER -d $DATABASE -f $DDL_FILE

# grant permission
PGPASSWORD=$PASSWORDADMIN psql -h $HOST -p $PORT -U $ADMINUSER -d $DATABASE << EOF
GRANT CONNECT ON DATABASE $DATABASE TO $NORMALUSER;
GRANT USAGE ON SCHEMA $SCHEMA TO $NORMALUSER;
GRANT USAGE, SELECT ON ALL sequences IN SCHEMA $SCHEMA TO $NORMALUSER;
GRANT ALL ON ALL TABLES IN SCHEMA $SCHEMA TO $NORMALUSER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA $SCHEMA TO $NORMALUSER;
EOF
